### PR TITLE
skin

### PR DESCRIPTION
**Pull request by eoli3n**
Hi Arthur,

I modified ompd_default/styles.css to pass every colors in css vars.
Now, make a skin is more easy, you just need to change vars value at the top of the file.
Some TODO things : 
- still some html color codes not in variable, but it doesnt impact skinnability
- pass "background-color:rgba()" in vars too
- clean last vars, misc/temp (read the file)
- maybe modify skin selector by just including those vars, let template as is
- clean every "WARNING" color vars

A new dark red skin, from ompd_default new template is added.
I didnt edit ompd_the_first, which use the previous template.

Hope you will enjoy,
Bye

### CODE REVIEW

**Comment by ArturSierzant** [comment]
Hi,
thank you very much for your work - you've made a big step forward to ease the creation of skins. And skin you've created looks great!

I've played with it and here are my ideas/notices:
* I've been thinking about modifications of skins for some time. My idea is: there should be one file styles_inc.css (with styles definitions) for all skins, placed in, say, ompd/skin dir. Each skin should have separate dir with its own file (called e.g. styles.css) with colors (and maybe fonts) definitions.  In styles.css there should be import rule to include 'master' style file (like @import url("skin/styles_inc.css")), font-face definitions (maybe) and all colors definitions (:root from your file). That way adding new style would be a matter of editing one master file - not all styles.css like now. 
* By the way: the same should be done with files template.header/footer.php - they are basicly the same for all styles and should not be duplicated like now. They should be moved to one dir /ompd/skin or maybe /ompd/include - of course it requires modifications of some other files.
* Unfortunately not all browsers support vars in css. Since I care for compatibility with as many browsers as possible (at least with its newest versions) maybe better idea would be using some preprocessor like http://lesscss.org/ ? Less allows client-side usage, so it's not nessesery to pre-compile code during development. I haven't tested it yet, but maybe its performance would be good enough to use client-side in 'production' too...
* I think one thing needs to be fixed: colors in default skin doesn't distinguish links and normal text, e.g. in 'now playing': track number, time, song title when no other versions found; headers on 'library'  page - now it all is blue, while blue should be only links, rest of text should be 'grey'.
* There is something wrong with your pull request - dir ompd_dark_red is empty (I use one you mailed me)

How about it?

Regards

**Comment by eoli3n** [comment]
Thx for your answer.
I searched about importing css file, and tried it but i read lots of warning about that, an example
https://www.stevesouders.com/blog/2009/04/09/dont-use-import/

Lesscss seems good, i will take a look at that and try some things.

I did the modification of font color to match dark_red skin template. A dark skin is hard to match exactly the "light" skin, cause of opposing light font with dark background, and dark font on light background. I will fix it in any way, thx.

I will close that pull request, then make a newer one with fixes, a working one :)
If you have more ideas, put it there.

Have a nice day.

**Comment by eoli3n** [comment]
Ok, so if i replace vars as in this example, will it be ok for you ?

[less2css test](http://less2css.org/#%7B%22less%22%3A%22%2F*%20vars%20*%2F%5Cn.bg-main()%20%7B%5Cn%20%20background%3A%20%232b2b2c%3B%5Cn%7D%5Cn%5Cn.bg-banner()%20%7B%5Cn%20%20color%3A%20%23cb4b16%3B%5Cn%7D%5Cn%5Cn%5Cn%5Cn%5Cn%2F*%20css%20body%20*%2F%5Cnbody%20%7B%5Cn%20%20margin%3A%200%20auto%3B%5Cn%20%20.bg-main()%3B%5Cn%20%20.bg-banner()%3B%5Cn%7D%22%7D)

**Comment by ArturSierzant** [comment]
I've just been playing with less and came to some conclusions:
* client-side usage causes some issues with other scripts on page (e.g. search form is visible by default, album covers are not scaled properly, etc.). Besides, compiling is performed every time a page is loaded (I thought it would be cached somehow, but not) and takes up to 600ms on my comp - quite long. So let's forget about it...
* much better is using .less files and pre-compile them to one style.css, which will be placed in skin folder. I've prepared a pair of such files (http://ompd.pl/downloads/less/skin.zip): _styles_inc.less_ contains all styles definitions, _styles.less_ contains all variables. Compiled file (_styles.css_) is used in all pages, like so far. I think this could be quite flexible and convenient: when you add new style definition, you do it only once (in _styles_inc.less_) and then complile all styles files in one move (I used WinLess for testing). 

Please try this and tell me what you think. In my opinion this could be the target solution for styling.

**Comment by eoli3n** [comment]
- ompd_default recreated with new template
- font links corrected in default and dark_red
It's normally, graphically done, so please try deeply and tell me if you find some graphic bugs.
(styles_inc.less upgraded too)
https://github.com/eoli3n/OMPD/

Next, before pull request
- clean code (left html codes, misc/temp vars)
- create a third skin

What did you want to do with headers|footers ?

**Comment by eoli3n** [comment]
I found a bug when you're on an album page : favorite stars herite from tr.even td, tr.odd td, tr.select td the color of the star. (line 526).
But if i replace @font-second for the right var @buttons, it changes all subcollumn in others tables, like in settings menu. I didnt find the way to force star color without heriting from table color.

**Comment by ArturSierzant** [comment]
OK, I'll test it.

**Comment by ArturSierzant** [comment]
I was playing with new skins. I'm impressed - almost all works fine. Please take a look at my comments and modifications ('ArtS edit') in _styles_inc.less_ (http://ompd.pl/downloads/less/ompd.zip). In zip file I've also included corrected _library.inc.php_, which lets you see more tooltips (more in comments in _styles_inc.less_).
Now skin _ompd_default_ works correct - at least I can find no more issues. I also checked your dark skin - seems to look ok, but you might like to do some corrections of my edits - please take a look at this too.

**Comment by eoli3n** [comment]
Great :+1: 
no time for now, but i will check this next weekend or maybe this week

**Comment by ArturSierzant** [comment]
I forgot about 2 more details I noticed in the dark skin:
*  dialog boxes (e.g. login dialog)
* version check in _About page_ (click O!MPD 1.02 in footer)

In both cases font color might require correction - please check this too.

**Comment by eoli3n** [comment]
- dialog login box fixed, but i there any others dialog boxes that i didnt see ?
- version check fixed
- library.inc.php included : download box work great
https://github.com/eoli3n/OMPD/

**Comment by ArturSierzant** [comment]
I've found one more dialog: error. Try add new non-existing MPD and display its playlist (Now Playing) - error info should appear:
http://ompd.pl/downloads/less/error_message.png

**Comment by eoli3n** [comment]
fixed : https://github.com/eoli3n/OMPD/

**Comment by ArturSierzant** [comment]
Actually in default skin this part of menu looked like this:

def

so I changed a little bit _styles_inc.less_ and both _styles.less_ (changes marked as 'ArtS edit'):
* added new vars: `@bg-sub-banner-2`, `@bg-sub-sub-banner-2`
* defined this vars in both _styles.less_

Additionally I modified styles for dialog boxes (`@box-ok`, `@box-warning`, `@box-error`) and for readonly inputs (`@bg-readonly`). 

All changes are here: http://ompd.pl/downloads/less/skin-2.zip. Please try it out.

**Comment by eoli3n** [comment]
no time for now, but i'm on it ;)

**Comment by ArturSierzant** [comment]
OK, take your time :)

**Comment by ArturSierzant** [comment]
I included your excellent work in eada258. Thanks a lot for your contribution!

**Comment by eoli3n** [comment]
Wow, glad to hear that ! You're welcome

**Pull request closed without merging**
