### PR TITLE
[IMPROVEMENT] fixing memory issues in import/update procedure

### PR DESCRIPTION
**Pull request by othmar52**
instead of processing the whole music collection within one mysql-fetch-loop smaller
batchsizes gets processed. now there is NO(!!!) memory growth within importer-phase
`fileInfo()` at all. @see #9
Unfortunately the memory-usage of the previous importer-phase (`fileStructure()`) is
still a problematic starting point `> 100 MB` for `fileInfo()`.

further some massive code-cleanup regarding tag-processing had been done. I have separated the condition-shizzle to a separate file `includes/tagProcessor.inc.php` where each track-property has now a separate helper function.

further the `fileInfo()` progressbar in GUI did not grow on non-updated tracks which should be fixed now

TODO: make use of the new tag-processing where needed to remove duplicate code-mess
TODO: refactoring fileStructure() in terms of memory consumption

### CODE REVIEW

**Comment by ArturSierzant** [comment]
Your work is impressive - thank you. I hope you'll figure out the `fileStructure()` issue. I'll try your changes in a few days.

**Comment by othmar52** [comment]
btw i have added another configuration value e137cdd33dac89ed7703c6715fa870eafeba8069
``` php
$cfg['debug_memory']                = false;
```
in case this is set to true each line of the debug output gets prefixed with memory usage
<pre>
<strong>[41.3M]</strong> fileInfo: [280475] /var/lib/mpd/music/testfile 01.mp3
<strong>[41.3M]</strong> fileInfo: [280475] /var/lib/mpd/music/testfile 02.mp3
<strong>[41.3M]</strong> fileInfo: [280475] /var/lib/mpd/music/testfile 03.mp3
<strong>[41.3M]</strong> Update stop time: 20161204 19:38:19
</pre>

**Comment by ArturSierzant** [comment]
Thanks for this - did you manage to import your music collection?

**Comment by othmar52** [comment]
> Thanks for this - did you manage to import your music collection?


importing a part with approx. 100 GB did work. Then I noticed that the import process does not recognize the majority of my bitmaps @see #17

I wanted to dig into that myself but when i sit in front of O!MPD's horrible code i am not willing to do anything for it until the code structure goes in a maintainable direction :)

Thats the reason why i created that much pull requests.
So currently i am waiting to have the image issue solved before i try to import more data.

**Pull request merged**
